apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: paymentmaker
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: paymentmaker
            image: bitgrinmining/services:latest
#            command: ["sleep", "9999999"]
            command: ["/usr/local/bin/paymentMaker.py"]
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          restartPolicy: Never
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
